This is a PlantUML file (http://plantuml.com/).

@startuml

skinparam monochrome true

:Read PCM buffer;

note right
    A PCM steam is written to a buffer
    and flushed every time the pipeline
    successfully finished it's job.
end note

fork
    :Average amplitude;

    note left
        Directly maps
        to the output volume.
    end note

fork again
    partition "Feature vector extraction" {
        fork
            partition "Prosodic features" {
                partition "Signal enhancing" {
                    :Filtering;
                    :Framing;
                    :Windowing;
                }

                fork
                    :Zero crossing time;
                fork again
                    :Short time energy;
                fork again
                    :Pitch;
                end fork
            }

        fork again
            partition "Spectral features" {
                :LPCC;

                note right
                    Linear prediction
                    cepstral coefficients.
                end note

                :Dimension reduction;
            }

        end fork
    }

    partition "Neural network" {
        :Emotion recognition;

        note right
            This is an R^n -> R^2 image.
        end note
    }

partition "Music composition" {
    fork
        :Tempo;

        note right
            Proportional to
            the emotion arousal.
        end note
    fork again
        :Scale;

        note right
            As a classification
            of the emotion valence.
        end note
    end fork
}

end fork

:MIDI generation;

note right
    The chord progressions themselves go here.
    Initially pink noise and frequency-induced
    chords should suffice.
end note

:Playback;

@enduml
